/*
 * Copyright (c)  Salem Bouraoui .
 *  Adapted For own use from Tutorial at : https://spring.io/guides/tutorials/rest/.
 *  Released for educational purposes only as a supplement to PluralSights Angular - Getting Started Course.
 *  I am not responsible for any direct or indirect misuse of this software and any related
 *  consequences. Use at your own risk.
 */

package com.triassic.systems.ps.dk.ng.gs.testserver.persistence.model;


import jakarta.persistence.Entity;
import jakarta.persistence.Id;

/**
 * this is a JPA Persistence Entity for our Product
 */

@Entity
public class Product {
    @Id
    private Long productId;
    private String productName;
    private String productCode;
    private String releaseDate;
    private String description;
    private Double price;
    private Double starRating;
    private String imageUrl;

    /**
     * This is the default constructor needed by our spring boot application
     */
    public Product()
    {

    }

    /**
     *  Constructor that defines all properties
     * @param productId
     * @param productName
     * @param productCode
     * @param releaseDate
     * @param description
     * @param price
     * @param starRating
     * @param imageUrl
     */
    public Product(Long productId,String productName,
                   String productCode,
                   String releaseDate,
                   String description,
                   Double price ,
                   Double starRating,
                   String imageUrl)
    {
        this.productId = productId;
        this.productName = productName;
        this.productCode = productCode;
        this.releaseDate = releaseDate;
        this.description = description;
        this.price = price;
        this.starRating = starRating;
        this.imageUrl = imageUrl;
    }


    /**
     *  Constructor that defines all properties except the Id which is then auto generated by the persistence instance
     * @param productName
     * @param productCode
     * @param releaseDate
     * @param description
     * @param price
     * @param starRating
     * @param imageUrl
     */
    public Product(String productName,
                   String productCode,
                   String releaseDate,
                   String description,
                   Double price ,
                   Double starRating,
                   String imageUrl)
    {
        this.productName = productName;
        this.productCode = productCode;
        this.releaseDate = releaseDate;
        this.description = description;
        this.price = price;
        this.starRating = starRating;
        this.imageUrl = imageUrl;
    }
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getStarRating() {
        return starRating;
    }

    public void setStarRating(Double starRating) {
        this.starRating = starRating;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getProductId() {
        return productId;
    }
}
